In [1]:
#Loading libraries
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np

In [2]:
data = load_breast_cancer()

In [3]:
data.keys()


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [5]:
data['data']

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [7]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
import pandas as pd

pd.DataFrame(data['data'], columns = data['feature_names'])

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [9]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [11]:
scaling = StandardScaler()

In [12]:
feature = scaling.fit_transform(data['data'])

In [13]:
pd.DataFrame(feature,columns = data['feature_names'])

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0       1.097064     -2.073335  ...        2.750622                 1.937015
1       1.829821     -0.353632  ...       -0.243890                 0.281190
2       1.579888      0.456187  ...        1.152255                 0.201391
3      -0.768909      0.253732  ...        6.046041                 4.935010
4       1.750297     -1.151816  ...       -0.868353                -0.397100
..           ...           ...  ...             ...                      ...
564     2.110995      0.721473  ...       -1.360158                -0.709091
565     1.704854      2.085134  ...       -0.531855                -0.973978
566     0.702284      2.045574  ...       -1.104549                -0.318409
567     1.838341      2.336457  ...        1.919083                 2.219635
568    -1.808401      1.221792  ...       -0.048138                -0.751207

[569 rows x 30 columns]

In [14]:
# Traimimg data(500)
X_train = feature[:500]
Y_train = data['target'][:500]




# validation data(35)
X_val = feature[500:535]
Y_val = data['target'][500:535]



# Testing data(34)
X_test = feature[535:]
Y_test = data['target'][535:]

In [15]:
feature[:500].shape

(500, 30)

In [16]:
data['target'][:500].shape

(500,)

In [17]:
X_train.shape

(500, 30)

In [18]:
X_val.shape

(35, 30)

In [19]:
X_test.shape

(34, 30)

In [20]:
# Creating Empty Stack to add layers
model = Sequential()
# Adding layers to model
# 30 layers as input and 1 layer as output
model.add(Dense(64, activation = 'relu' ,input_dim = 30))
model.add(Dense(48, activation = 'relu'))


model.add(Dense(1,activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [21]:
model.fit(X_train,Y_train,batch_size = 1, epochs = 10, validation_data = (X_val, Y_val))

Epoch 1/10
500/500 [==============================] - 2s 2ms/step - loss: 0.1616 - accuracy: 0.9460 - val_loss: 0.0480 - val_accuracy: 1.0000
Epoch 2/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0651 - accuracy: 0.9820 - val_loss: 0.0778 - val_accuracy: 0.9714
Epoch 3/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0498 - accuracy: 0.9880 - val_loss: 0.1217 - val_accuracy: 0.9714
Epoch 4/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0391 - accuracy: 0.9880 - val_loss: 0.0918 - val_accuracy: 0.9714
Epoch 5/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0270 - accuracy: 0.9900 - val_loss: 0.2075 - val_accuracy: 0.9714
Epoch 6/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0408 - accuracy: 0.9800 - val_loss: 0.1197 - val_accuracy: 0.9714
Epoch 7/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0294 - accuracy: 0.9920 - val_loss: 0.0600 - val_accuracy: 0.9714
Epoch 

In [22]:
model.evaluate(X_test,Y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.0598 - accuracy: 0.9706


[0.0597781166434288, 0.970588207244873]

In [23]:
model.evaluate(X_val,Y_val)

2/2 [==============================] - 0s 8ms/step - loss: 0.1649 - accuracy: 0.9714


[0.16490912437438965, 0.9714285731315613]

In [24]:
Y_test

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [25]:
Y_val

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [26]:
sample = X_test[0]

In [27]:
sample.shape

(30,)

In [28]:
sample

array([ 1.82414032,  0.36543133,  1.88778669,  1.85751441,  0.58638323,
        1.31824626,  1.50283863,  2.14814488,  1.15143953, -0.04077169,
        1.05904307, -0.4114087 ,  0.910827  ,  1.04382537, -0.82102626,
        0.03810891,  0.27043808,  0.3915519 , -0.12862155, -0.41830962,
        1.66304049, -0.03211657,  1.57682617,  1.63207582, -0.24410428,
        0.37681708,  0.82091153,  1.5256103 ,  0.28512459, -0.45750286])

In [37]:
model.predict(sample)

array([[1.2336515e-18]], dtype=float32)

In [34]:
sample = np.reshape(sample,(1,30))

  

In [30]:
sample.shape

(30,)

In [35]:
model.predict(sample)

array([[1.2336515e-18]], dtype=float32)

In [36]:
 if model.predict(sample)[0][0]>0.5:
   print('Benign')
 else:
   print("Malignant")  

Malignant


In [ ]:
0-Malignant
1-De

In [ ]:
X_test[10]

array([-0.14407806,  0.91694624, -0.19684934, -0.23233219, -0.27756523,
       -0.6987597 , -0.741488  , -0.6316726 , -0.53894726, -0.67869351,
       -0.21356438,  0.21617286, -0.39605381, -0.20015129, -0.39100882,
       -0.25084001, -0.38739725, -0.44317904,  0.03967757, -0.45840426,
       -0.19034815,  0.55574951, -0.28836304, -0.26506358, -0.47205092,
       -0.65245698, -0.80257043, -0.65270672, -0.41860997, -0.7988643 ])